version: "3"
services:
  web:
    image: 27051997/cdac
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8107:8000"
    networks:
      - webnet
  ditiss:
    image: arunvel1988/cdac
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8418:8000"
    networks:
      - webnet
networks:
  webnet:





